#! /bin/csh -f
#############################################################################
#
# Script to compare working code version on RPi to configured version
#
#############################################################################
#
# Specify root where old version exists
#set ROOT="/media/${USER}/305f60b3-8413-4edb-afc1-4e4ce064aab3/home/${USER}"
#set ROOT="/media/${USER}/pi"
#set ROOT="/media/${USER}/aa2il"
set ROOT="/media/${USER}/marconi"
#set ROOT="/media/${USER}/sproul"
set ROOT="/mnt/sproul"
#set ROOT="/media/${USER}/3D76-ECB1"
#set ROOT="/media/${USER}/acer"
#set ROOT="/media/${USER}/cartman"
#set ROOT="../clone"
if( !(-e $ROOT) )then
    set ROOT="${ROOT}2"
endif

# Add path down to old version
set N=`echo $HOME | wc -c`
echo N=$N
#set PTH=`pwd | cut -c ${N}-`
set PTH=`pwd | sed 's/\/home2//g' | cut -c ${N}-`
echo PTH=$PTH
set old=${ROOT}${PTH}
echo OLD=$old

# Overide if necessary
#set old="NEW"

rm -f DIFFS
set PREDICT="pypredict-1.7.0"
foreach i (*.py *.txt $PREDICT/*.c  $PREDICT/*.py  $PREDICT/JBA work/* DIFF *.bat trsp/Moon.trsp trsp/None.trsp)
    echo $i
    set n=`diff $old/$i $i | wc -l`
    if( !( -e $old/$i ) )then
        echo NO SUCH FILE $old/$i
        cp $i $old/$i
    else if( $n > 0 ) then
        echo ---------------------------------- >> DIFFS
        echo $i >> DIFFS
        echo " " >> DIFFS
        diff -w $old/$i $i >> DIFFS
        echo " " >> DIFFS
        
        #kompare $old/$i $i
        kompare $i $old/$i
    endif
end

chmod +x pySat.py DIFF

cat DIFFS
