#! /bin/csh -f

# Specify root where old version exists
set ROOT="/media/joea/305f60b3-8413-4edb-afc1-4e4ce064aab3/home/joea"
set ROOT="/media/joea/pi"

# Add path down to old version
set N=`echo $HOME | wc -c`
echo N=$N
set PTH=`pwd | cut -c ${N}-`
echo PTH=$PTH
set old=${ROOT}${PTH}
echo OLD=$old

rm -f DIFFS
foreach i (*.c *.py)
    echo $i
    set n=`diff -w $old/$i $i | wc -l`
    if( $n>0 ) then
        echo ---------------------------------- >> DIFFS
        echo $i >> DIFFS
        echo " " >> DIFFS
        diff -w $old/$i $i >> DIFFS
        echo " " >> DIFFS
        
        kompare $old/$i $i
    endif
end

cat DIFFS
